#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


SOURCE_FILENAMES = [
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
    ".mobile-superpowers/component-contract.md",
    ".mobile-superpowers/project-constraints.md",
]

UI_KEYWORDS = [
    "ui",
    "widget",
    "component",
    "dialog",
    "text",
    "button",
    "theme",
    "color",
    "spacing",
    "typography",
    "design",
    "flutter",
    "android",
    "ios",
    "组件",
    "弹窗",
    "文本",
    "按钮",
    "主题",
    "颜色",
    "间距",
    "设计",
    "禁止",
    "必须",
    "不得",
]

REQUIREMENT_KEYWORDS = [
    "must",
    "required",
    "require",
    "use ",
    "forbidden",
    "forbid",
    "avoid",
    "instead",
    "禁止",
    "必须",
    "不得",
    "统一使用",
    "使用",
]

COMPONENT_RE = re.compile(r"\b(?:Common[A-Za-z0-9_]+|AppColors|AppSpacing|AppTheme|ThemeData)\b")
FORBIDDEN_ALIASES = {
    "raw Text": "Text(",
    "Text": "Text(",
    "AlertDialog": "AlertDialog",
    "Dialog(": "Dialog(",
    "ElevatedButton": "ElevatedButton",
    "FilledButton": "FilledButton",
    "Color(0x": "Color(0x",
}


def relpath(path: Path, base: Path) -> str:
    try:
        return path.resolve().relative_to(base.resolve()).as_posix()
    except ValueError:
        return path.resolve().as_posix()


def interesting_line(line: str) -> bool:
    lowered = line.lower()
    return any(keyword in lowered for keyword in UI_KEYWORDS) and any(
        keyword in lowered for keyword in REQUIREMENT_KEYWORDS
    )


def read_source_lines(project_dir: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for filename in SOURCE_FILENAMES:
        path = project_dir / filename
        if not path.exists() or not path.is_file():
            continue
        for index, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
            cleaned = line.strip()
            if cleaned and interesting_line(cleaned):
                records.append({"source": filename, "line": index, "text": cleaned[:320]})
    return records


def extract_required_components(lines: list[dict[str, Any]]) -> list[str]:
    found: set[str] = set()
    for record in lines:
        for component in COMPONENT_RE.findall(record["text"]):
            found.add(component)
    return sorted(found)


def extract_forbidden_patterns(lines: list[dict[str, Any]]) -> list[dict[str, str]]:
    found: dict[str, str] = {}
    for record in lines:
        text = record["text"]
        lowered = text.lower()
        for alias, pattern in FORBIDDEN_ALIASES.items():
            if alias.lower() in lowered:
                found[pattern] = infer_required_for_pattern(pattern)
    return [{"forbidden": key, "required": value} for key, value in sorted(found.items())]


def infer_required_for_pattern(pattern: str) -> str:
    if pattern in {"Text("}:
        return "CommonText"
    if pattern in {"AlertDialog", "Dialog("}:
        return "CommonDialog"
    if pattern in {"ElevatedButton", "FilledButton"}:
        return "CommonButton"
    if pattern == "Color(0x":
        return "AppColors or project theme tokens"
    return "project component contract"


def source_files(project_dir: Path) -> list[str]:
    return [filename for filename in SOURCE_FILENAMES if (project_dir / filename).is_file()]


def render_constraints_markdown(
    *,
    project_dir: Path,
    output: Path,
    style_skill: Path | None,
    lines: list[dict[str, Any]],
    required_components: list[str],
    forbidden_patterns: list[dict[str, str]],
) -> str:
    sources = source_files(project_dir)
    style_skill_text = relpath(style_skill, project_dir) if style_skill else "none"
    checker_cmd = (
        "python3 mobile-superpowers/scripts/mobile_component_contract_check.py "
        "--project-dir <project-dir> --platform flutter"
    )
    rendered = [
        "# Mobile Project Constraints",
        "",
        "Generated by `mobile_project_constraints.py`. Keep this file compact; reference source files instead of copying full agent instructions.",
        "",
        "## Source Files",
        "",
    ]
    if sources:
        rendered.extend(f"- `{source}`" for source in sources)
    else:
        rendered.append("- none discovered")
    rendered.extend(
        [
            "",
            "## Required Components And Tokens",
            "",
        ]
    )
    if required_components:
        rendered.extend(f"- `{component}`" for component in required_components)
    else:
        rendered.append("- none discovered")
    rendered.extend(
        [
            "",
            "## Forbidden Direct Usage",
            "",
            "| Forbidden | Required Replacement |",
            "|---|---|",
        ]
    )
    if forbidden_patterns:
        rendered.extend(f"| `{item['forbidden']}` | `{item['required']}` |" for item in forbidden_patterns)
    else:
        rendered.append("| none discovered | project patterns |")
    rendered.extend(
        [
            "",
            "## Extracted Constraint Lines",
            "",
        ]
    )
    if lines:
        for record in lines[:40]:
            rendered.append(f"- `{record['source']}:{record['line']}` {record['text']}")
        if len(lines) > 40:
            rendered.append(f"- ... {len(lines) - 40} additional matching lines omitted.")
    else:
        rendered.append("- none discovered")
    rendered.extend(
        [
            "",
            "## Style Skill Binding",
            "",
            f"- Skill: `{style_skill_text}`",
            "- When a prompt names a project style skill, read and summarize only the mobile-relevant constraints before design or implementation.",
            "",
            "## HTML Baseline Semantics",
            "",
            "- HTML baselines cannot instantiate Flutter/Android/iOS widgets directly.",
            "- Mark mapped elements with `data-platform-component`, for example `CommonText`, `CommonButton`, or `CommonDialog`.",
            "",
            "## Verification Commands",
            "",
            f"- `{checker_cmd}`",
            "",
        ]
    )
    return "\n".join(rendered)


def generate_project_constraints(
    *,
    project_dir: Path | str,
    output: Path | str | None = None,
    style_skill: Path | str | None = None,
) -> dict[str, Any]:
    project_dir = Path(project_dir).expanduser().resolve()
    output_path = (
        Path(output).expanduser().resolve()
        if output
        else project_dir / "docs" / "mobile-superpowers" / "project-constraints.md"
    )
    style_skill_path = Path(style_skill).expanduser().resolve() if style_skill else None
    errors: list[str] = []
    if not project_dir.exists():
        errors.append(f"project dir not found: {project_dir}")
    if style_skill_path and not style_skill_path.exists():
        errors.append(f"style skill not found: {style_skill_path}")
    lines = read_source_lines(project_dir) if not errors else []
    required_components = extract_required_components(lines)
    forbidden_patterns = extract_forbidden_patterns(lines)
    result = {
        "project_dir": str(project_dir),
        "output": str(output_path),
        "source_files": source_files(project_dir) if project_dir.exists() else [],
        "style_skill": str(style_skill_path) if style_skill_path else None,
        "component_contract": {
            "required_components": required_components,
            "forbidden_patterns": forbidden_patterns,
        },
        "validation": {"errors": errors, "warnings": []},
    }
    if errors:
        return result
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_constraints_markdown(
            project_dir=project_dir,
            output=output_path,
            style_skill=style_skill_path,
            lines=lines,
            required_components=required_components,
            forbidden_patterns=forbidden_patterns,
        ),
        encoding="utf-8",
    )
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate compact Mobile Superpowers project constraints.")
    parser.add_argument("--project-dir", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--style-skill", type=Path, default=None)
    parser.add_argument("--json", action="store_true", dest="json_output")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = generate_project_constraints(
        project_dir=args.project_dir,
        output=args.output,
        style_skill=args.style_skill,
    )
    if args.json_output:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(result["output"])
    for error in result["validation"]["errors"]:
        print(f"ERROR: {error}")
    return 1 if result["validation"]["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
