#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path
from typing import Any


CONTRACT_SECTIONS = [
    "Source Inputs",
    "Target Platform Assumptions",
    "HTML Baseline",
    "Screenshot And Metrics",
    "Layout Structure",
    "Visual Tokens",
    "Component Inventory",
    "State Coverage",
    "Asset Strategy",
    "Mobile Constraints",
    "Acceptable Deviations",
    "Must-Fix Differences",
    "Platform Handoff Notes",
]


def slugify(value: str) -> str:
    slug = value.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or "mobile-visual"


def titleize(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", " ", value).strip()
    return " ".join(part[:1].upper() + part[1:] for part in cleaned.split()) or "Mobile Visual"


def contract_scaffold(topic: str, workspace: Path, artifacts: dict[str, str]) -> str:
    title = titleize(topic)
    lines = [
        f"# {title} Visual Contract",
        "",
        "Generated by `mobile_visual_artifacts.py`.",
        "",
        "## Artifact Paths",
        "",
    ]
    for name, path in artifacts.items():
        lines.append(f"- `{name}`: `{path}`")
    lines.append("")
    for section in CONTRACT_SECTIONS:
        lines.extend([f"## {section}", ""])
        if section == "Asset Strategy":
            lines.extend(
                [
                    "- Use `code` for layout primitives, cards, buttons, simple dividers, simple backgrounds, and text.",
                    "- Use `icon` for platform/system icons or simple SVG/lucide-style pictograms.",
                    "- Use `image_asset` for photos, avatars, product imagery, brand marks, complex illustrations, textures, glass effects, and dense charts.",
                    "- Use `crop` when the asset should be cut from the reference or generated mockup.",
                    "- Use `regenerate` when the asset should be recreated by an image model before platform implementation.",
                    "- For each asset record: `name`, `strategy`, `source`, `target_path`, `dimensions`, `acceptable_deviation`, and `platform_notes`.",
                    "",
                    "| Asset | Strategy | Source | Target Path | Dimensions | Notes |",
                    "|---|---|---|---|---|---|",
                    "| Not recorded yet. |  |  |  |  |  |",
                    "",
                ]
            )
        else:
            lines.extend(["- Not recorded yet.", ""])
    return "\n".join(lines).rstrip() + "\n"


def create_visual_workspace(
    *,
    project_dir: Path | str = Path.cwd(),
    topic: str,
    date: str | None = None,
    force: bool = False,
) -> dict[str, Any]:
    project_dir = Path(project_dir).expanduser().resolve()
    day = date or globals()["date"].today().isoformat()
    workspace = project_dir / "docs" / "mobile-superpowers" / "visual" / f"{day}-{slugify(topic)}"
    workspace.mkdir(parents=True, exist_ok=True)

    artifacts = {
        "reference": str(workspace / "reference.png"),
        "generated_mockup": str(workspace / "generated-mockup.png"),
        "baseline_html": str(workspace / "baseline.html"),
        "baseline_screenshot": str(workspace / "baseline-screenshot.png"),
        "baseline_metrics": str(workspace / "baseline-metrics.json"),
        "visual_contract": str(workspace / "visual-contract.md"),
    }

    contract = Path(artifacts["visual_contract"])
    if force or not contract.exists():
        contract.write_text(contract_scaffold(topic, workspace, artifacts), encoding="utf-8")

    manifest = workspace / "artifacts.json"
    manifest.write_text(
        json.dumps({"workspace": str(workspace), "topic": topic, "date": day, "artifacts": artifacts}, indent=2),
        encoding="utf-8",
    )

    return {"workspace": str(workspace), "topic": topic, "date": day, "artifacts": artifacts}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a Mobile Superpowers visual artifact workspace.")
    parser.add_argument("--project-dir", type=Path, default=Path.cwd())
    parser.add_argument("--topic", required=True)
    parser.add_argument("--date", default=None)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--json", action="store_true", dest="json_output")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = create_visual_workspace(
        project_dir=args.project_dir,
        topic=args.topic,
        date=args.date,
        force=args.force,
    )
    if args.json_output:
        print(json.dumps(result, indent=2))
    else:
        print(result["workspace"])
        print(result["artifacts"]["visual_contract"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
